# docker-compose.dev.yaml
services:
  tee:
    extends:
      file: docker-compose.base.yaml
      service: tee
    build:
      context: .
      dockerfile: Dockerfile
      target: development
      args:
        - NODE_ENV=development
    volumes:
      - ./agent:/app/agent:delegated
      - ./packages:/app/packages:delegated
      - /app/agent/node_modules
      - /app/packages/node_modules
      - ./scripts:/app/scripts
      - ./characters:/app/characters
      - tweet-cache:/app/packages/client-twitter/src/tweetcache
      - db-data:/app/db.sqlite
    env_file:
      - .env.dev

volumes:
  tweet-cache: {}
  db-data: {}
